homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 739
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_glob: !include custom-ui.yaml

# Custom UI from https://github.com/andrey-git/home-assistant-custom-ui
customizer:
  custom_ui: local

# Enables the frontend
frontend:
 themes:
  material_dark_green:
   light_green: "#08a8a5"
   dark_green: "#017775"
   dark_grey: "#232326"
   light_grey: "#344249"

   red: "#d10404"
   yellow: "#fffa0c"
   white: "#f7f7f7"
   pink: "#ff0090"

#Top bar, activate text on script, selected icon on home assistant menu, top panel of media players, text in config page, text on developer tools states page, mqtt publish text, logbook text
   primary-color: "var(--light_green)"
# divider on dev tools info page
   light-primary-color: "var(--red)"
# some hyperlinked text
   dark-primary-color: "var(--red)"
# not sure where used
   text-primary-color: "var(--pink)"
# main background, top of side panel
   primary-background-color: "var(--dark_grey)"
# not sure where used 
   sidebar-text_-_background: "var(--pink)"
# card background colour, part of media player background
   paper-card-background-color: "var(--light_grey)"
# mqtt pubish header and thats it 
   paper-card-header-color: "var(--white)"
# main background colour of states page
   secondary-background-color: "var(--dark_grey)"
# most of the text used
   primary-text-color: "var(--white)"
#secondary pieces of text 
   secondary-text-color: "var(--white)"
#main background of side panel 
   paper-listbox-background-color: "var(--light_grey)"
#not sure where used
   paper-toggle-button-checked-ink-color: "var(--pink)"
#switch colour when on
   paper-toggle-button-checked-button-color: "var(--yellow)"
#Backgroud of switch/toggle when on
   paper-toggle-button-checked-bar-color: "var(--yellow)"
#slide knob on brightness/volumes when not 0
   paper-slider-knob-color: "var(--yellow)"
#slide knob on brightness/volumes when 0
   paper-slider-knob-start-color: "var(--red)"
#don't know where used
   paper-slider-pin-color: "var(--pink)"
#colour of brightness/volume slider line in used portion 
   paper-slider-active-color: "var(--yellow)"
#not sure where used
   paper-slider-secondary-color: "var(--pink)"
# background of brightness/volume slider line not used portion 
   paper-slider-container-color: "var(--red)"
#not sure where used
   paper-progress-secondary-color: "var(--pink)"
#background of theme selection toggle tiny use 
   paper-item-selected_-_background-color: "var(--light_green)"
#text, not sure which one "var(--white)"
   paper-item-icon_-_color: "var(--pink)"
# icon on state page when off
   paper-item-icon-color: "var(--dark_green)"
#states icon when active 
   paper-item-icon-active-color: "var(--yellow)"
#colour of switch toggle when off, icon on selected page of menu 
   paper-grey-50: "var(--light_green)"
#background of selected screen on menu "var(--light_green)"
   paper-grey-200: "var(--dark_green)"
#Backgound of label icon
   label-badge-background-color: "var(--light_grey)"
#colour of text in label icon 
   label-badge-text-color: "var(--white)"
#colour of edge of sensor labels
   label-badge-red: "var(--red)"
#not sure where used
   label-badge-blue: "var(--pink)"
   label-badge-green: "var(--pink)"
   label-badge-yellow: "var(--pink)"
   label-badge-grey: "var(--pink)"
# Row 1 on entities page
   table-row-background-color: "var(--light_grey)"
# row 2 on entities page
   table-row-alternative-background-color: "var(--dark_grey)"

# Enables configuration UI
config:

automation: !include automations.yaml

#secrets: !include secrets.yaml

scene: !include scenes.yaml

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
   base_url: !secret baseurl
   ssl_certificate: !secret sslcert
   ssl_key: !secret sslkey

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
  ignore:
  - netgear_router
  - harmony

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Record events
recorder:

# Track the sun
sun:

ffmpeg:

script: !include scripts.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml

#usps: !include usps.yaml

ifttt:
   key: !secret ifttt

bloomsky:
   api_key: !secret bloomsky

device_tracker:
  - platform: netgear
    host: 192.168.1.1
    username: !secret router_user
    password: !secret router_pwd

climate:
   platform: honeywell
   username: !secret honeywell_user
   password: !secret honeywell_pwd
   scan_interval: 600
   region: us

remote:
  - platform: harmony
    name: Harmony Hub den
    host: 192.168.1.9

remote 1:
 - platform: harmony
   name: Harmony Hub bed
   host: 192.168.1.21

mqtt:
  broker: localhost
  #discovery: true
  #discovery_prefix: smartthings
  port: 1883

alarm_control_panel:
  platform: mqtt
  state_topic: "smartthings/alarm system status/alarmSystemStatus"
  command_topic: "smartthings/alarm system status/alarmSystemStatus"
  name: "SHM"
  payload_disarm: "disarmed"
  payload_arm_home: "armed_home"
  payload_arm_away: "armed_away"

light: !include light.yaml

switch: !include switches.yaml

input_boolean: !include input_booleans.yaml

binary_sensor: !include binary_sensors.yaml

sensor: !include sensors.yaml

lock:
   platform: mqtt
   name: "Front Door Lock"
   state_topic: "smartthings/Front Door Lock/lock"
   command_topic: "smartthings/Front Door Lock/lock"
   payload_lock: "locked"
   payload_unlock: "unlocked"
   retain: true

media_player:
 - platform: onkyo
   host: 192.168.1.25

media_player 1:
 - platform: kodi
   host: 192.168.1.60
   port: 8383
   username: kodi
   password: !secret kodi
   name: "Kodi Den"

media_player 2:
 - platform: braviatv
   host: 192.168.1.29

media_player 3:
 - platform: cast

media_player 4:
 - platform: plex

media_player 5:
 - platform: kodi
   host: 192.168.1.23
   port: 6363
   username: kodi
   password: !secret kodi
   name: "Kodi Bedroom"

amcrest:
 #- host: 192.168.1.42
 #  port: 1025
 #  username: admin
 #  password: !secret boogie
 #  name: "Den Camera"

 - host: 192.168.1.41
   port: 1026
   username: admin
   password: !secret boogie
   name: "Living Room Camera"

 - host: 192.168.1.36
   port: 1027
   username: admin
   password: !secret boogie1
   name: "Outdoor Camera"

camera:
 - platform: mjpeg
   mjpeg_url: http://192.168.1.46/img/video.mjpeg
   name: "Kitchen Camera"

 - platform: amcrest

 - platform: ring

notify:
 - platform: nfandroidtv
   name: Den
   host: 192.168.1.29

 - platform: nfandroidtv
   name: Kitchen
   host: 192.168.1.52

 - platform: nfandroidtv
   name: Bedroom
   host: 192.168.1.23

 - platform: html5
   name: chrome
   gcm_api_key: !secret gcm_api_key
   gcm_sender_id: !secret gcm_sender_id

ring:
   username: !secret ringuser
   password: !secret ringpass

google:
   client_id: !secret google_client_id
   client_secret: !secret google_secret_key

google_assistant:
  project_id: hass-ga-908cf
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  exposed_domains:
  - switch
  - light
  - script
  - scene

namecheapdns:
  host: plex
  domain: !secret namecheap_site
  password: !secret namecheap_pw