name: Home
views:
- icon: mdi:home
  title: Home
  cards:
  - type: picture-glance
    image: 
    camera_image: camera.den_camera
    title: Den
    entities:
    - switch.den_fan
    - light.den_lights_level
    - switch.fireplace
    - remote.harmony_hub_den
    - light.tv_lights
    - binary_sensor.den_sliding_door
    - binary_sensor.den_window
    - sensor.den_air_purifier_temp
  - type: picture-glance
    image: 
    camera_image: camera.kitchen_camera
    title: Kitchen
    entities:
    - light.bar_flex
    - light.cabinet_lights
    - light.counter_lights
    - switch.island_lights_switch
    - light.kitchen_lights_level
    - switch.kitchen_tv
    - binary_sensor.kitchen_window
    - sensor.kitchen_window
  - type: picture-glance
    image:
    camera_image: camera.living_room_camera
    title: Living
    entities:
    - lock.front_door_lock_locked
    - switch.living_room_fan
    - light.living_room_lights_level
    - binary_sensor.front_door
    - binary_sensor.living_room_left_bay_window
    - binary_sensor.living_room_right_bay_window
    - binary_sensor.living_room_side_window
    - sensor.living_room_air_purifier_temp
  - type: entities
    title: Vacuums
    show_header_toggle: false
    entities:
    - vacuum.mr_neato
    - vacuum.mrs_neato
  - type: entities
    title: BBQ
    entities:
    - input_select.bbq_probe1
    - input_number.bbq1_override
    - sensor.bbq1temperature
    - binary_sensor.bbq1
  - type: entities
    title: Thermostat
    entities:
    - climate.thermostat_cooling_1
    - climate.thermostat_heating_1
  - type: entity-filter
    card:
      title: People Home
      type: glance
    entities:
    - binary_sensor.dannys_bayesian_presence
    - binary_sensor.natachas_bayesian_presence
    state_filter:
    - 'on'
    show_empty: false
- title: Room
  icon: mdi:home-modern
  cards:
  - type: entities
    title: Bedroom
    show_header_toggle: false
    entities:
    - switch.bedroom_fan
    - light.bedroom_lights_level
    - light.biased_lights
    - light.dannys
    - remote.harmony_hub_bed
    - light.toshs
    - binary_sensor.bedroom_closet_door
    - binary_sensor.bedroom_door
    - binary_sensor.bedroom_motion_sensor
    - binary_sensor.bedroom_window
    - sensor.bedroom_air_purifier_aqi
    - sensor.bedroom_air_purifier_humidity
    - sensor.bedroom_air_purifier_temp
    - sensor.bedroom_closet_door
    - sensor.bedroom_illumination_sensor
    - sensor.bedroom_smoke_status
    - sensor.bedroom_window
  - type: picture-glance
    image:
    camera_image: camera.office_camera
    title: Office
    entities:
    - light.hallway_light
    - light.office_closet
    - light.office_lights
    - binary_sensor.office_closet_door
    - binary_sensor.office_window
    - sensor.office_window
  - type: entities
    title: Bathroom
    show_header_toggle: false
    entities:
    - light.bathroom_night_light
    - binary_sensor.bathroom_door
    - binary_sensor.bathroom_sink_leak_sensor
    - binary_sensor.bathroom_window
    - sensor.bathroom_humidity
    - sensor.illumination_34ce0091f546
    - sensor.bathroom_pressure
    - sensor.bathroom_temperature
    - sensor.bathroom_window
  - type: picture-glance
    image:
    camera_image: camera.outdoor_camera
    title: Garage
    entities:
    - switch.garage_lights_switch
    - binary_sensor.garage_backyard_door
    - binary_sensor.garage_frontyard
    - sensor.dryer_power_2
    - sensor.pool_pump_power
    - sensor.washer_power_2
  - type: entities
    title: Backyard
    show_header_toggle: false
    entities:
    - switch.backyard_lights_switch
    - light.fig_tree_lights
    - light.firepit_lights
    - light.garden_lights
    - light.patio
  - type: entities
    title: House Settings
    show_header_toggle: false
    entities:
    - alarm_control_panel.home
    - input_boolean.guest_mode
    - input_boolean.movie_mode
    - input_boolean.night_mode
    - input_boolean.shower_mode
    - input_boolean.vacation_mode
- title: Automations
  icon: mdi:home-automation
  cards:
  - type: "custom:monster-card"
    title: All Automations
    filter:
      include:
      - domain: automation
    card:
      type: entities
      title: All Automations
      show_header_toggle: false
  - type: "custom:monster-card"
    title: All Scripts
    card:
      type: entities
      title: All Scripts
      show_header_toggle: false
    filter:
      include:
      - domain: script
- title: Services
  icon: mdi:home-circle
  cards:
  - type: entities
    title: Pi-Hole
    entities:
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_dns_queries_today
    - sensor.pihole_ads_percentage_blocked_today
    - sensor.pihole_domains_blocked
  - type: glance
    title: SABnzbd
    entities:
    - entity: sensor.sabnzbd_disk
      name: Disk
    - entity: sensor.sabnzbd_disk_free
      name: Disk Free
    - entity: sensor.sabnzbd_left
      name: Left
    - entity: sensor.sabnzbd_queue
      name: Queue
    - entity: sensor.sabnzbd_speed
      name: Speed
    - entity: sensor.sabnzbd_status
      name: Status
  - type: glance
    title: Ring
    entities:
    - entity: binary_sensor.ring_front_door_ding
      name: Door Ding
    - entity: binary_sensor.ring_front_door_motion
      name: Door Motion
    - entity: binary_sensor.ring_side_gate_motion
      name: Gate Motion
    - entity: sensor.ring_front_door_battery
      name: Door Battery
  - type: glance
    title: Weather Station
    entities:
    - entity: binary_sensor.shokabow_weather_night
      name: Night
    - entity: binary_sensor.shokabow_weather_rain
      name: Rain
    - entity: sensor.shokabow_weather_humidity
      name: Humidity
    - entity: sensor.shokabow_weather_luminance
      name: Luminance
    - entity: sensor.shokabow_weather_pressure
      name: Pressure
    - entity: sensor.shokabow_weather_temperature
      name: Temperature
    - entity: sensor.shokabow_weather_uvindex
      name: UV Index
    - entity: sensor.shokabow_weather_voltage
      name: Voltage
  - type: entities
    title: Forecast
    entities:
    - sensor.pws_weather
    - sensor.pws_alerts
    - sensor.pws_feelslike_f
    - sensor.pws_weather_1d
    - sensor.pws_weather_1n
    - sensor.pws_weather_2d
    - sensor.pws_weather_2n
    - sensor.pws_weather_3d
    - sensor.pws_weather_3n
  - type: glance
    title: Epson Printer Info
    entities:
    - entity: sensor.epson_ink_level_black
      name: Black
    - entity: sensor.epson_ink_level_cyan
      name: Cyan
    - entity: sensor.epson_ink_level_magenta
      name: Magenta
    - entity: sensor.epson_ink_level_yellow
      name: Yellow
    - entity: sensor.epson_ink_level_photo_black
      name: Photo
  - type: glance
    title: Speed Test
    entities:
    - entity: sensor.speedtest_ping
      name: Ping
    - entity: sensor.speedtest_download
      name: Download
    - entity: sensor.speedtest_upload
      name: Upload
  - type: entities
    title: ZoneMinder
    show_header_toggle: false
    entities:
    - switch.den_state
    - switch.garage_state
    - switch.kitchen_state
    - switch.living_room_state
  - type: glance
    title: PlantLink Artichoke
    entities:
    - entity: sensor.artichoke_status
      name: Status
    - entity: sensor.artichoke_last_updated
      name: Last Update
    - entity: sensor.artichoke_next_water
      name: Next Water
    - entity: sensor.artichoke_fuel
      name: Fuel
    - entity: sensor.artichoke_moisture
      name: Moisture
    - entity: sensor.artichoke_signal
      name: Signal
    - entity: sensor.artichoke_battery
      name: Battery
- title: Media Players
  icon: mdi:cast
  cards:
  - type: media-control
    entity: media_player.bedroom_speaker
  - type: media-control
    entity: media_player.bathroom_speaker
  - type: media-control
    entity: media_player.den_home
  - type: media-control
    entity: media_player.den_tv
  - type: media-control
    entity: media_player.home_notification
  - type: media-control
    entity: media_player.house
  - type: media-control
    entity: media_player.kitchen_home
  - type: media-control
    entity: media_player.kodi_bedroom
  - type: media-control
    entity: media_player.kodi_den
  - type: media-control
    entity: media_player.kodi_kitchen
  - type: media-control
    entity: media_player.kodi_outdoor
  - type: media-control
    entity: media_player.living_room_home
  - type: media-control
    entity: media_player.office_speaker
  - type: media-control
    entity: media_player.onkyo_den
  - type: media-control
    entity: media_player.outdoor_speakers
  - type: media-control
    entity: media_player.sony_bravia_tv
  - type: media-control
    entity: media_player.stream_unlimited9639
- title: Calendar
  icon: mdi:calendar
  cards:
  - type: entities
    title: Calendar Sensors
    entities:
    - sensor.danny_next_event
    - sensor.tosh_next_event
    - sensor.danny_next_meeting
    - sensor.next_us_holiday
    - sensor.next_jewish_holiday

resources:
  - url: /local/monster-card.js
    type: js